require:
- ./spec/linters/migration/add_constraint_name.rb

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - vendor/**/*
    - lib/diego/bbs/models/**/*

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Lint/UnifiedInteger:
  Exclude:
    - db/migrations/**/*

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/migrations/**/*
    - spec/**/*
    - lib/cloud_controller/config.rb
    - config/routes.rb
    - lib/tasks/db.rake
  Max: 50

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Performance/Sample:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/AlignParameters:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FileName:
  Exclude:
    - Guardfile

Style/FormatString:
  EnforcedStyle: sprintf

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineArrayBraceLayout:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineHashBraceLayout:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantSelf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/StructInheritance:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
